---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'arrangodb deployment nested stack'
Parameters:
  Environment:
    Type: String
  ConfigFile:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  AmiId:
    Type: String
  Subnets:
    Type: String
  CertificateArn:
    Type: String
  InstanceType:
    Type: String
  AlbType:
    Type: String
  DefaultSecurityGroup:
    Type: String
  MgmtSecurityGroup:
    Type: String
  UISecurityGroup:
    Type: String
  EfsSecurityGroup:
    Type: String
  AlbSecurityGroup:
    Type: String
  KeyPair:
    Type: String
  BucketName:
    Type: String
  MountTargetIps:
    Type: String
  MountTargetIp2:
    Type: String
    Description: unused placeholder
Conditions:
  CertificateExists: !Not [!Equals ['', !Ref CertificateArn ] ]
Resources:
  Efs:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/ss-vsts-codepipeline-${AWS::Region}/vsts/${AWS::AccountId}/deployment/scout2/templates/efs.yaml'
      Parameters:
        PrivateSubnets: !Ref Subnets
        MountTargetIps: !Ref MountTargetIps
        VpcId: !Ref VpcId
        EfsSecurityGroup: !Ref EfsSecurityGroup
        VolumeName: !Sub "EFS-Scout2-${Environment}"
  Scout2Management:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/ss-vsts-codepipeline-${AWS::Region}/vsts/${AWS::AccountId}/deployment/scout2/templates/scout2-mgmt.yaml'
      Parameters:
        Environment: !Ref Environment
        ConfigFile: !Ref ConfigFile
        PrivateSubnets: !Ref Subnets
        InstanceType: !Ref InstanceType
        AmiId: !Ref AmiId
        KeyPair: !Ref KeyPair
        DefaultSecurityGroup: !Ref DefaultSecurityGroup
        MgmtSecurityGroup : !Ref MgmtSecurityGroup
        MountTargetIps: !Ref MountTargetIps
        BucketName: !Ref BucketName
  Scout2Ui:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/ss-vsts-codepipeline-${AWS::Region}/vsts/${AWS::AccountId}/deployment/scout2/templates/scout2-ui.yaml'
      Parameters:
        Environment: !Ref Environment
        PrivateSubnets: !Ref Subnets
        InstanceType: !Ref InstanceType
        AmiId: !Ref AmiId
        KeyPair: !Ref KeyPair
        DefaultSecurityGroup: !Ref DefaultSecurityGroup
        UISecurityGroup: !Ref UISecurityGroup
        MountTargetIps: !Ref MountTargetIps
        TargetGroupId: !GetAtt Alb.Outputs.TargetGroup
  Alb:
    Condition: CertificateExists
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/ss-vsts-codepipeline-${AWS::Region}/vsts/${AWS::AccountId}/deployment/scout2/templates/LoadBalancer.yaml'
      Parameters:
        Name: !Sub 'scout2-${Environment}'
        AlbType: !Ref AlbType
        Vpc: !Ref VpcId
        Subnets: !Ref Subnets
        AlbSecurityGroup: !Ref AlbSecurityGroup
        CertificateArn: !Ref CertificateArn
